name        : libidn
version     : 1.32
release     : 3
source     :
    - http://ftp.gnu.org/gnu/libidn/libidn-1.32.tar.gz : ba5d5afee2beff703a34ee094668da5c6ea5afa38784cebba8924105e185c4f5
license     :
    - GPLv2+
summary     : Internationalized domain name support library
description : |
    GNU library implementing Stringprep, Punycode and IDNA specifications.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
