name       : libidn
version    : 1.34
release    : 7
source     :
    - https://ftp.gnu.org/gnu/libidn/libidn-1.34.tar.gz : 3719e2975f2fb28605df3479c380af2cf4ab4e919e1506527e4c7670afff6e3c
license    :
    - GPL-2.0-or-later
    - LGPL-3.0-or-later
component  : network.library
summary    : Internationalized domain name support library
description: |
    GNU library implementing Stringprep, Punycode and IDNA specifications.
emul32     : yes
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
