name       : libidn
version    : 1.33
release    : 5
source     :
    - http://ftp.gnu.org/gnu/libidn/libidn-1.33.tar.gz : 44a7aab635bb721ceef6beecc4d49dfd19478325e1b47f3196f7d2acc4930e19
license    : GPL-2.0
component  : network.library
summary    : Internationalized domain name support library
description: |
    GNU library implementing Stringprep, Punycode and IDNA specifications.
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
