name       : libidn
version    : 1.32
release    : 4
source     :
    - http://ftp.gnu.org/gnu/libidn/libidn-1.32.tar.gz : ba5d5afee2beff703a34ee094668da5c6ea5afa38784cebba8924105e185c4f5
license    :
    - GPL-2.0
summary    : Internationalized domain name support library
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
description: |
    GNU library implementing Stringprep, Punycode and IDNA specifications.
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
