name       : libidn
version    : '1.38'
release    : 10
source     :
    - https://ftp.gnu.org/gnu/libidn/libidn-1.38.tar.gz : de00b840f757cd3bb14dd9a20d5936473235ddcba06d4bc2da804654b8bbf0f6
license    :
    - GPL-2.0-or-later
    - LGPL-3.0-or-later
component  : network.library
summary    : Internationalized domain name support library
description: |
    GNU library implementing Stringprep, Punycode and IDNA specifications.
emul32     : yes
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
