name       : libidn
version    : 1.35
release    : 8
source     :
    - https://ftp.gnu.org/gnu/libidn/libidn-1.35.tar.gz : f11af1005b46b7b15d057d7f107315a1ad46935c7fcdf243c16e46ec14f0fe1e
license    :
    - GPL-2.0-or-later
    - LGPL-3.0-or-later
component  : network.library
summary    : Internationalized domain name support library
description: |
    GNU library implementing Stringprep, Punycode and IDNA specifications.
emul32     : yes
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
